### ISSUE TITLE
Set service name.

### ISSUE THREAD

**Issue by pedrofurla** [instana/haskell-trace-sdk#1]
We at CompStak are missing the service name setting.

**Comment by basti1302** [comment]
Hi Pedro,

I would like to understand your request a little bit better.Do you want to map _individual calls_ to different service names, similar to what we outline here https://docs.instana.io/products/application_service_management/#using-the-call-tag-servicename for other runtime platforms (Java, Python, Go, ...)?

Kind regards

  Bastian

**Comment by goedelsoup** [comment]
i think in the interim just overriding the default hostname would be useful. this is a microservice we'll lean on, so visibility into it is pretty critical for us. we don't necessarily need individual calls split, but having control over the service name would be useful.

**Comment by basti1302** [comment]
I'll probably pick this up some time this week or early next week.

**Comment by basti1302** [comment]
This has landed in version `0.3.0.0`.

You now can
- override the default service name by setting the environment variable `INSTANA_SERVICE_NAME`, or
- override the default service name by passing it as a configuration option when using `InstanaSDK.initConfiguredInstana`, or
- override the service name extraced from individual spans be calling `InstanaSDK.setServiceName` while the span is active.

I also published another change I needed to make with version 0.3.0.0 and unfortunately it is a breaking change, so you might need to update a few API calls. Please see <https://github.com/instana/haskell-trace-sdk/blob/master/ChangeLog.md#0300> for details.
